services:
  school-web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionStrings__DefaultConnection=Data Source=db/school.db"
      - sqldata:/app/db
    restart: unless-stopped

volumes:
  sqldata:
